spring:
  application:
    name: Efficient Inventory
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory
    username: root

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8989


